Repository wecode-bootcamp-korea/41-2nd-CalPick-frontend, pull requests merged in 2023-02, with the labels that each got.

#5 [41기 하평안] 공용 컴포넌트 useFetch 생성
  public/data/data.json
  src/hooks/useFetch.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#6 [41기 하평안] Nav 레이아웃 구현
  package-lock.json
  package.json
  public/images/logo.png
  src/components/Nav/Components/NavCategoriesIcon.jsx
  src/components/Nav/Components/NavCategoriesIcon.styles.js
  src/components/Nav/Components/NavCategory.jsx
  src/components/Nav/Components/NavCategory.styles.js
  src/components/Nav/Components/NavLogin.jsx
  src/components/Nav/Components/NavLogin.styles.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.styles.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#1 [41기 이진경] Feature : colors 컨벤션 수정 완료 (피드백 수정 완료)
  .env.sample
  src/components/Button.js
Labels: 완료

#9 [41기 서지연] Add: modal 컴포넌트 생성 & Modify: input 컴포넌트 onChange 함수 추가 & font-family 추가
  src/components/Button.js
  src/components/Input.js
  src/components/Modal.js
  src/styles/GlobalStyle.js
Labels: 완료

#8 [41기 서지연] Add: selected 페이지 레이아웃 구현완료 & Modify: Button 컴포넌트 수정
  public/data/seats.json
  src/Router.js
  src/pages/Selected/Selected.js
  src/pages/Selected/Selected.styles.js
  src/pages/Selected/components/SelectForm.jsx
  src/pages/Selected/components/SelectForm.styles.js
  src/pages/Selected/components/SelectSeat.jsx
  src/pages/Selected/components/SelectSeat.styles.js
  src/pages/Selected/components/UserInfo.jsx
  src/pages/Selected/components/UserInfo.styles.js
Labels: 완료

#13 [41기 서지연] mypage layout 구현 완료 & input 컴포넌트 수정
  public/data/testInfo.json
  public/data/userInfo.json
  src/Router.js
  src/components/Input.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/Profile/Profile.jsx
  src/pages/Mypage/Profile/Profile.styles.js
  src/pages/Mypage/Scores/Scores.jsx
  src/pages/Mypage/Scores/Scores.styles.js
Labels: 멘토 리뷰 요청, Rebase 요청

#15 [41기 하평안] useDate Hook 구현
  src/hooks/useDate.js
Labels: 멘토 리뷰 요청

#16 [41기 서지연] mypage 기능 구현 완료
  src/pages/Mypage/Profile/Profile.jsx
  src/pages/Mypage/Scores/Scores.jsx
Labels: 멘토 리뷰 요청

#7 [41기 이진경] Feature : 구글 로그인 기능 구현 완료 (버튼 컴포넌트 수정 완료)
  .gitignore
  package-lock.json
  package.json
  public/images/sample.png
  src/Router.js
  src/components/Button.js
  src/index.js
  src/pages/Login/SocialLogin/Redirect.js
  src/pages/Login/SocialLogin/SocialLogin.js
  src/pages/Login/SocialLogin/SocialLogin.styles.js
Labels: 완료

#12 [41기 이진경] Feature: 시험 리스트 페이지 기능 구현 완료
  public/data/data.json
  src/Router.js
  src/pages/ExamInfo/ExamInfo.js
  src/pages/ExamList/Components/ExamPlan/ExamPlan.jsx
  src/pages/ExamList/Components/ExamPlan/ExamPlan.styles.js
  src/pages/ExamList/Components/ExamPlanList/ExamPlanList.jsx
  src/pages/ExamList/Components/ExamPlanList/ExamPlanList.styles.js
  src/pages/ExamList/ExamList.js
  src/pages/ExamList/ExamList.styles.js
Labels: 멘토 리뷰 요청

#19 [41기 김우성] Add: Footer 레이아웃 구현 완료
  public/images/arrow.png
  public/images/center.png
  public/images/facebook.png
  public/images/instagram.png
  public/images/megaphone.png
  public/images/youtube.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.styles.js
Labels: 멘토 리뷰 요청

#23 [41기 이진경] Update : navigate 함수 경로 수정 완료
  src/pages/ExamList/Components/ExamPlanList/ExamPlanList.jsx
Labels: 멘토 리뷰 요청

#17 [41기 김우성] Add: 로그인 페이지 및 기능구현
  src/Router.js
  src/components/Input.js
  src/pages/Login/Login.js
  src/pages/Login/Login.styles.js
Labels: 멘토 리뷰 요청

#11 [41기 서지연] 버튼 컴포넌트 수정, 예약하기 기능 구현완료
  .gitignore
  config.js
  package-lock.json
  package.json
  public/data/reservationInfo.json
  public/images/facebook.png
  public/images/instagram.png
  public/images/youtube.png
  src/components/Button.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.styles.js
  src/config.js
  src/hooks/useInput.js
  src/pages/Selected/Selected.js
  src/pages/Selected/Selected.styles.js
  src/pages/Selected/components/SelectForm.jsx
  src/pages/Selected/components/SelectForm.styles.js
  src/pages/Selected/components/SelectSeat.jsx
  src/pages/Selected/components/SelectSeat.styles.js
  src/pages/Selected/components/UserInfo.jsx
  src/pages/Selected/components/UserInfo.styles.js
Labels: 완료

#25 [41기 서지연] order페이지 구현 완료
  src/Router.js
  src/pages/Order/Order.js
  src/pages/Order/Order.styles.js
Labels: 멘토 리뷰 요청

#22 [41기 서지연] certification layout & pdf 기능 구현 완료
  package-lock.json
  package.json
  public/data/certification.json
  public/images/verify.png
  src/Router.js
  src/components/Footer/Footer.styles.js
  src/pages/Certification/Certification.js
  src/pages/Certification/Certification.styles.js
Labels: 수정 요청

#26 [41기 서지연] Modify: 스타일 vh 수정 완료, certification 오류 수정 완료
  src/pages/Certification/Certification.js
  src/pages/Certification/Certification.styles.js
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/Scores/Scores.styles.js
  src/pages/Order/Order.styles.js
  src/pages/Selected/Selected.styles.js
  src/pages/Selected/components/UserInfo.jsx
Labels: 멘토 리뷰 요청

#24 [41기 이진경] Feat: 카카오 로그인 구현 완료
  src/Router.js
  src/index.js
  src/pages/Login/KakaoLogin/KaKaoLogin.js
  src/pages/Login/KakaoLogin/OAUTH.js
  src/pages/Login/Login.js
  src/pages/Login/Login.styles.js
  src/pages/Login/SocialLogin/Redirect.js
  src/pages/Login/SocialLogin/SocialLogin.js
  src/pages/Login/SocialLogin/SocialLogin.styles.js
Labels: 멘토 리뷰 요청

#10 [41기 이진경] Feature : 시험 접수 페이지 레이아웃 구현 완료 / 카카오 map api 기능 구현중
  .env
  public/data/ExamList.json
  public/index.html
  src/Router.js
  src/components/Button.js
  src/hooks/useFetch.js
  src/pages/ExamInfo/Components/InfoTable/Components/TableList/Components/ TestSite.jsx
  src/pages/ExamInfo/Components/InfoTable/Components/TableList/TablaList.jsx
  src/pages/ExamInfo/Components/InfoTable/Components/TableList/TableList.styles.js
  src/pages/ExamInfo/Components/InfoTable/InfoTable.jsx
  src/pages/ExamInfo/Components/InfoTable/InfoTable.styles.js
  src/pages/ExamInfo/Components/MapInfo/Components/MapContainer.jsx
  src/pages/ExamInfo/Components/MapInfo/Components/MapContainer.styles.js
  src/pages/ExamInfo/Components/MapInfo/MapInfo.jsx
  src/pages/ExamInfo/Components/MapInfo/MapInfo.styles.js
  src/pages/ExamInfo/Components/SelectedInfo/SelectedInfo.jsx
  src/pages/ExamInfo/Components/SelectedInfo/SelectedInfo.styles.js
  src/pages/ExamInfo/ExamInfo.js
  src/pages/ExamInfo/ExamInfo.styles.js
  src/pages/ExamList/Components/ExamPlan/ExamPlan.jsx
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#14 [41기 하평안] Add : 캘린더 기능 구현, 레이아웃 구현, 백엔드 API 개발 후 통신 필요
  package-lock.json
  package.json
  public/data/testAll.json
  public/data/userCalendar.json
  src/Router.js
  src/components/Footer/Footer.styles.js
  src/components/Label.js
  src/components/Nav/Nav.styles.js
  src/pages/Calendar/Calendar.js
  src/pages/Calendar/Calendar.styles.js
  src/pages/Calendar/Components/CalendarCheckBox.jsx
  src/pages/Calendar/Components/CalendarLibrary.jsx
  src/pages/Calendar/Components/CalendarLibrary.styles.js
  src/pages/Calendar/Components/CalendarModal.jsx
  src/pages/Calendar/Components/CalendarModal.styles.js
  src/pages/Calendar/Components/CalendarStatusModal.jsx
  src/pages/Calendar/Components/CalendarStatusModal.styles.js
  src/pages/Calendar/Components/CalenderCheckBox.styles.js
  src/pages/Login/Login.js
  src/pages/Main/Components/Card.jsx
  src/pages/Main/Main.js
  src/pages/Main/Main.styles.js
Labels: 추가 기능 구현 중
